Update filebot-watcher

diff --git a/filebot-watcher b/filebot-watcher
--- a/filebot-watcher
+++ b/filebot-watcher
@@ -14,6 +14,13 @@ inotifywait -m "$1" -e create -e moved_to -e modify --exclude '/[.@]' --format '
 	# e.g. video.mp4: video/mp4
 	if file --mime-type "$FILE" | egrep "directory|video|audio|empty|octet-stream"; then
 		filebot -script fn:amc --action duplicate --conflict auto -non-strict --log-file amc.log --def excludeList=".excludes" unsorted=y music=y artwork=y "$@"
+		rc=$?	
 		filebot -script fn:cleaner "$1"
+		if [[ $rc != 0 ]]; then		
+			cat /data/filebot.log | mutt -F /muttrc -s 'Filebot Error' canibis313@gmail.com
+		else
+			cat /data/filebot.log | mutt -F /muttrc -s 'Filebot successfully ended' canibis313@gmail.com
+		fi
+		rm -rf /data/filebot.log
 	fi
 done
